### ISSUE TITLE
Add .codeinventory file IAW GSA github/opensource policy

### ISSUE THREAD

**Issue by briankfitzwater** [GSA/ansible-os-rhel-7#11]
However, I can no longer find the policy document that prescribes this.  Has this requirement gone away?

**Comment by jeremy-gillikin** [comment]
@afeld I'm not of aware of this requirement. Do you have any info?

**Comment by briankfitzwater** [comment]
The file is used by GSA to meet 7.2 of the Federal Open Source Policy.

Example:

```yaml
name: 'CodeInventory Metadata Generator'
description: 'Generates project metadata files that can be used to build an organization-wide code inventory.'
license: null
openSourceProject: 1
governmentWideReuseProject: 1
tags:
    - open-source
    - code.gov
contact:
    email: cto@gsa.gov
```

There appear to be three related GSA projects on GitHub:
- [codeinventory-metadata-generator](https://github.com/GSA/codeinventory-metadata-generator)
- [codeinventory](https://github.com/GSA/codeinventory)
- [codeinventory-github](https://github.com/GSA/codeinventory-github)
